/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#e2e2e2',
        'surface-container-lowest': '#0c0f0f',
        'primary-fixed-dim': '#e9c349',
        'on-secondary-fixed-variant': '#39475f',
        secondary: '#b9c7e4',
        'tertiary-fixed': '#d8e2ff',
        error: '#ffb4ab',
        'surface-bright': '#37393a',
        'surface-container': '#1e2020',
        surface: '#121414',
        outline: '#99907c',
        'surface-tint': '#e9c349',
        tertiary: '#becef5',
        'on-primary-fixed': '#241a00',
        'tertiary-fixed-dim': '#b6c6ed',
        'on-secondary-fixed': '#0d1c32',
        'on-primary-fixed-variant': '#574500',
        'error-container': '#93000a',
        background: '#121414',
        'inverse-primary': '#735c00',
        'on-error-container': '#ffdad6',
        'outline-variant': '#4d4635',
        primary: '#f2ca50',
        'on-tertiary-container': '#354565',
        'surface-container-low': '#1a1c1c',
        'inverse-on-surface': '#2f3131',
        'on-tertiary-fixed': '#091b39',
        'surface-container-high': '#282a2b',
        'on-tertiary-fixed-variant': '#374767',
        'on-secondary': '#233148',
        'on-surface-variant': '#d0c5af',
        'on-surface': '#e2e2e2',
        'on-tertiary': '#20304f',
        'primary-fixed': '#ffe088',
        'on-primary-container': '#554300',
        'primary-container': '#d4af37',
        'on-secondary-container': '#abb9d6',
        'surface-container-highest': '#333535',
        'on-error': '#690005',
        'secondary-fixed': '#d6e3ff',
        'on-primary': '#3c2f00',
        'surface-dim': '#121414',
        'secondary-container': '#3c4962',
        'secondary-fixed-dim': '#b9c7e4',
        'tertiary-container': '#a3b3d8',
        'on-background': '#e2e2e2',
        'surface-variant': '#333535',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '2rem',
        section: '8rem',
        gutter: '24px',
        base: '8px',
        xl: '4rem',
        md: '1rem',
        sm: '0.5rem',
        xs: '0.25rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['1rem', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        h1: ['4.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h3: ['2rem', { lineHeight: '1.3', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['0.75rem', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        h2: ['3rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
